# Generated by Django 4.2.1 on 2023-05-05 23:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Importado'), (3, 'Sistema')], default=1, null=True)),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, 'Arma'), (2, 'Carro'), (3, 'Computador'), (4, 'Viatura policial')])),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
                'db_table': 'objeto',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('eh_policial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'db_table': 'pessoa',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPossePessoaObjeto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('basic_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Importado'), (3, 'Sistema')], default=1, null=True)),
                ('eh_de_policia', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objeto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.objeto')),
                ('pessoa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.pessoa')),
            ],
            options={
                'verbose_name': 'historical Posse da Pessoa',
                'verbose_name_plural': 'historical Posses da Pessoa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalObjeto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('basic_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('data_modificacao', models.DateTimeField(blank=True, editable=False, null=True)),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Importado'), (3, 'Sistema')], default=1, null=True)),
                ('descricao', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, 'Arma'), (2, 'Carro'), (3, 'Computador'), (4, 'Viatura policial')])),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Objeto',
                'verbose_name_plural': 'historical Objetos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PossePessoaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, null=True)),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Manual'), (2, 'Importado'), (3, 'Sistema')], default=1, null=True)),
                ('eh_de_policia', models.BooleanField(default=False)),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posses_por_pessoa', to='inventario.objeto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posses_por_pessoa', to='inventario.pessoa')),
            ],
            options={
                'verbose_name': 'Posse da Pessoa',
                'verbose_name_plural': 'Posses da Pessoa',
                'db_table': 'posse_pessoa_objeto',
                'unique_together': {('pessoa', 'objeto')},
            },
        ),
    ]
