# Generated by Django 4.2.1 on 2023-05-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_arma_alter_historicalpossepessoaobjeto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpossepessoaobjeto',
            name='eh_de_policia',
        ),
        migrations.RemoveField(
            model_name='possepessoaobjeto',
            name='eh_de_policia',
        ),
    ]
