# Generated by Django 4.2.8 on 2023-12-21 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0001_initial'),
        ('objeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possepessoaobjeto',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posses_por_pessoa', to='pessoa.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='historicalpossepessoaobjeto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpossepessoaobjeto',
            name='objeto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='objeto.objeto', verbose_name='Objeto'),
        ),
        migrations.AddField(
            model_name='historicalpossepessoaobjeto',
            name='pessoa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoa.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='historicalobjeto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='possepessoaobjeto',
            unique_together={('pessoa', 'objeto')},
        ),
    ]
