CHOICE_ARMA = 1
CHOICE_CARRO = 2
CHOICE_COMPUTADOR = 3
CHOICE_VIATURA_POLICIAL = 4

CHOICES_TIPOS_OBJETOS = (
    (CHOICE_ARMA, 'Arma'),
    (CHOICE_CARRO, 'Carro'),
    (CHOICE_COMPUTADOR, 'Computador'),
    (CHOICE_VIATURA_POLICIAL, 'Viatura policial'),
)
